server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reactivesw
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
