server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactivesw
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.rai.jsonb.dialet.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update